import java.util.*;
class Game{
    void method(){
        try (Scanner s = new Scanner(System.in)) {
            int guess,k=10,i=0,score=100;
            int rand=1+(int)(100*Math.random());
            while(i<10){
                System.out.println("Guess the number: ");
                guess = s.nextInt();
                if(guess>1 && guess<100){
                    if(rand==guess){
                        System.out.println("Congratulations!...You are correct\n Your score is: "+score);
                        break;
                    }
                    else if(rand>guess){
                        System.out.println("number is greater");
                        
                    }
                    else if(rand<guess){
                        System.out.println("number is lesser");
                    }
                    score=score-10;
                    i=i+1;
                }
                else{
                    System.out.println("Your number is out of range");
                }
            }
            if(i==k){
                System.out.println("Sorry...but your chances are completed...");
            }
            System.out.println("Do you wanna play again?...\nPress 1 to play or 0 to exit");
            int end=s.nextInt();
            if(end==1){
                method();
            }
            else{
                System.out.println("THANK YOU...");
            }
        }
    }
}
public class Number_Guess{
   public static void main(String args[]){
        Game g = new Game();
        System.out.println("***********Welcome***********");
        System.out.println("Game rules:");
        System.out.println("1.The system generates a random number form 1 to 100 \n2.You have to guess the number that is generated by the system\n3.You will be given 10 chances to guess the number\n4.For every wrong guess your score will be reduced by 10\n");
        g.method();
    }
}